language: minimal

branches:
  only:
    - travis_ci_docker

services:
  - docker

env:
  global:
    # The following encrypted variables were created by the commands 'travis encrypt storepass=STORE_PASSWORD'
    - secure: x5cPm8yMQHQ6Zd7OSMtxYZfICGyrSZFJP1Ra81AFqOwe6SYnakzZnS4vzXJskEs4QVr63NdXpqVQVmeU03spNbg8fDznL5zRW0MxEMlCvdKPeJl/MRehIgrkuHrmOhkpI4+g1r5YDLSw17lFS5Ms3ZZr1JP2u2MStXzPlMbgpScz+3h3XteHG34flTtvCh5lXsB2epZroYrzA2h8i+3CRCC9daPS4p1/1gkFdxE519sEg88IbsqRxkdXkV63XcAE86WnEJjwVJs/sO+RvdTg1bAAogA8d7HpmtLof+eMD/Ig87UAoHdYnyGBFjpEZGqgvAAknrpKYZn9ma6hSB9cWl5+C9BZjSDxnGHgC2JZ5GwCqzuY65DzQGT2vBiZd+pNmvZtGywoMoHNypbXBzBRd42DsjE2DKPmrZtqyJ4YOL4/BVmUDN0EwpX4EH0NfsHYkNCfxelm8U/0OXIYcTpzVaRL5vXwiP90mURn6F9TmQdboMqeao8+fJS3sQfAhlgELl9TnQGOfiQ2XnzdhFcq7L5nxGhNpDhL2jxkYw6WvEbfyW3n0iSHjF2CCF4e3vpi9W5lDnrO2JaFBPobqTNSYs24w0uf30cXerTfaGG+Fl1pYTQ2SOmrxlHR1dRiy9I/xr1NIZA/rCZE0coikKkdce5D1kTjs+6oF8oMxiY9PfA=
    # The following encrypted variables were created by the commands 'travis encrypt keypass=KEY_PASSWORD'
    - secure: vL7JHK994prRwVUPmbzfs3aTVJTiZJz3zK3h5bThVDWzQJhzuQBtVOfpjuFOjMeCuIhEje33yyAKngqpqjUm80SwMFri9wL1bvyZ0kWTgEBzajZAn+kKt+uaX5bjAATRVQAnLQwNnNgHfiJATiEPGRf3J9DWpKOBl/nsSxJ8H0oSt9GNany6kYls9Jspqbe1kA4JH7q8Qkr2RhKOhyScE3vjbUjJZzxyedXJu8Qqvf88yqxVvPBLRE3jI97dzVDJ4SG8KtAP1h6+um9Lp1apUEmfII0xwqkXxq3v2ksHB2KC+Q/l5ndQ8cq2qJyZfVNvkW6ib6ldZiNsmSaNUVT/JacQAd2lyYdo73rGc5NIDb/OpEW9gB3gtR1yhcQYopjsWMmaU+DCA9IOLWiD9NV2APmWUFKuiFa2dkQPR6sUQauS7KFrLdgSs8IJyXCRO5DMwy+G9hMiyFFie5KlJtimImzLJhCysZa81rJiQMDz5tgDIw0SmNfU9ymRxwUpWtVP1FnReoK/lFxcR5Ud0id8X9m8/vhwt+9E2mAfNpCjn7FKbUT+FqovkX8IKWzFaHu0YYs3IOmsdMKeNCYsGv7sRtmpmj7zoztlwDD7YT4G1oy9X2HgHxydvY/blZNFKwnbsnzcWvsC+eJH3mmSbvAum7GKWGLzjz73lteI5RnxVUI=

before_install:
  # The encrypted keystore file as wel as the following command was created by the command 'travis encrypt-file keystore.jks'.
  - "openssl aes-256-cbc -K $encrypted_78b319501daa_key -iv $encrypted_78b319501daa_iv -in keystore.jks.enc -out keystore.jks -d"
  - docker build -f docker/Dockerfile -t yacguide . > docker_build.log || tail -n 100 docker_build.log
  - docker volume create yacguide

script:
  - docker run --name yacguide --volume yacguide:/mnt/yacguide-build yacguide docker/build.sh "$storepass" "$keypass" > build.log || tail -n 100 build.log
  - docker cp yacguide:/mnt/yacguide-build/dist/yacguide.apk .

before_deploy: mv yacguide.apk yacguide-${TRAVIS_TAG}.apk

deploy:
  provider: releases
  api_key:
    secure: "rJAEGK92d9jR/Gm0n8hlLCzHXIIzUV9V1cDXYo6kycGizHZRxuOy6txlTEQfOucTLtpUPxMHj8dKa6M+6vYoCU6dQDixecn7WU90jXlGuf2XItTl9Vac81R6fUUhcfS2NyKr8fDgw3I7bfnZ59K3bi1uY95pBpSX6ISsaSFd3kydqTPkHVw4Kqb15NnOseWPwPrW27WI1Bd73D8KLvzReH8QadluYQr1qlNj8HbpTsHDZweRG9vsQTo90y/eedg8HTILEAmv5PrDB0m3pne9SraP+jG7FZE3es5Rw5J7ZO1o48tQ2aCDQY5wU2u2xTvA6RU+mLO3yb58nAIOuPxhIIEoAPv45Ha2cy1xF115HXCUtdZDhcUSIGMf/UvnOocBHKIcbV9t7tS92HMlqYvxGdXqZ52zBVKMQFojyKSfr0nUlmvz6Lu0zZ9TQ6QwbarrcX5IZIbTzMUKXqpcmMiaB0KRbPVjmFAO3hMpjnbEEfpNpBoPTk45AD2YX3cZ6xiQEZM5ogRNLvbNMaMad9nVctz6OORGOVlG3M3SCBsu/PX3sbNwGNx4ajs4bMckMd70gGDKXbNN6ScAJrObUlYIcY9J1aj/VYZLpCG1FtDWUlnbWZ0RrhmCvY2TYykW/tU8/F75LNkeXc4+I0t5smz79/b3l8v3EYazxgwO24H085I="
  file: "yacguide-${TRAVIS_TAG}.apk"
  skip_cleanup: true
  on:
    tags: true
