language: minimal

services:
  - docker

script:
  # Build unsigned APK file for both flavors
  - make docker-run docker-prep
  - make apk-build FLAVOR=stable
  - make apk-build FLAVOR=dev
  - make docker-stop
