language: shell
os: linux
dist: xenial

services:
  - docker

before_script:
  # Decode Google Service Account JSON file
  - echo $playServicesFileBase64 | base64 -d > $playServicesFile
  # Decode keystore file from variable
  - echo $playKeyStoreBase64 | base64 -d > $playKeyStore
  # Write keystore properties file
  - printf 'storeFile=%s\nstorePassword=%s\nkeyAlias=%s\nkeyPassword=%s\nplayServicesFile=%s\n'
    $playKeyStore $playStorePassword $playKeyAlias $playKeyPassword $playServicesFile > keystore.properties
  # Prepare Docker cotainer
  - make docker-run docker-prep

script:
  - make tests dists

after_script:
  - make docker-stop

before_deploy:
  - make docker-start-existing

deploy:
  - provider: script
    skip_cleanup: true
    script: make deploy-play-dev
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^dev-[0-9]{8}$

after_deploy:
  - make docker-stop
