language: minimal

services:
  - docker

env:
  global:
    # The following encrypted variables were created by the commands 'travis encrypt storepass=STORE_PASSWORD'
    - secure: "ridXteqFu/9spKElColeY1+nbptKn7dpESA2dgOgQFaVUAajZ9sRyYkgnAiHVPZYrcBf55mqe1VkYceEPsO4A4YOb+f7y7e/awZaUdBkzw6hLT8T3gSZ1IVY8VmYtfWzX6UxoPNK2uELRYWg4JopZ3EeV2y2OsHK1rFAuRTpbWa4Hmh/1IfL0LCFUb5NgbjH1ltaCGgrdKTojTEUy3dk011+tf1NAXkvqocP5pdBuo85DDzblKKNfTqvXTrfEX9Hmkxlxb/2PMZAScL3WYC5Kg6BXRBg6ctyLL+ambBbqUJTxh5xeYCZn8b7F4Vhm2Qj4+nI6lbgvj/sE7658aSjGetjpCHhmCRvCa6Sujv+HEqLJN9aDru9q2fH7dGKJX7dQjmQJMUYfpe2ZH3rGOXS/dW3AMnUKau33ukkC4nCjI0EgmN3tkCA0usKYxpUfyvmgzlad+QCcZ3R/qLebziomNonluo8h7ctXuUhB7Fj+MREwikLIDRvOo1KZ50P0K7iPRy5LZJuzHghh0A5rLE9OVKQ6LFE9o/d3qhDlTnRNDQcTlsMuMvO1OP1pS7tI+oHA5D+g0rCalVjDkavnm8uVxuYQveMG/5g1Q8Y/VnxrErH6F6pP/33gTwxsOztjqvY4cgXTQY4C9kZ2Sy627XjePHyWNF2nieucUFKoUp+yWQ="
    # The following encrypted variables were created by the commands 'travis encrypt keypass=KEY_PASSWORD'
    - secure: "kbFc6OGjcqxHQdtV+G78ELlqEPE1x72QmD49zlIkhRXy2WtlGE2V0Vma/VaTkJbZRgmMW0b2V7Qr/JKtjBLp0SvToXeZRF++TKXwCncRXx8I8y3N9TRrfxU8VW/74ncj7lCUFbFVmiyinTHY1vVdLwgG8ChAFYQibOf8x0sY+5D4aojXRnTTRrr2m1vjG0R1ciMgIgyT8zpayiheeZVbbui2eUkkpqwlDKV0N3dVTffWWfE43AyLrqlHoROh4A8t/JGgOEIhj68uIv5DAIVyghQ8yJSdXrprn/AQ/u4iEhnIZ0cWzvu/h4CpyPu9FpzqhOdmweUb57yZe/7JOD79gmC201mqQpiiw2M+3STCmvEwELYuxB3whmyPTumVuawesg3nnN2h7fvdGFPmMapH94fkHIanlUZk0m1Sg0FEoKc1iD9L4V8CEIpyiNMCYUaLIUg5oOdfp78UQaD/lcYo1OV/iF0YayP4T49lM4mdkJydS/zeQi9Y6QBfnUs2IQbKvNFPWWx29M8mIar0wjy3l0PfBD8MMYD1zOdBMIJE+HftP6sQ50W4eW08dSpxfgcMnYSrTfngopXJWpWgV0m+tfHmHkAp7qEMNnB92Xh50zcKQ5UFMzEN4GI6WgyScGF62qEqr1TOkvUb+35kJYU8RF7f3TaVGWX0JpgapeW9eOU="

before_install:
  # The encrypted keystore file as well as the following command was created by the command 'travis encrypt-file keystore.jks'.
  - "openssl aes-256-cbc -K $encrypted_78b319501daa_key -iv $encrypted_78b319501daa_iv -in keystore.jks.enc -out keystore.jks -d"

script:
  - ./docker/build.sh "$storepass" "$keypass" > build.log || tail -n 100 build.log

before_deploy:
  # Remove leading 'v' from tag name to extract release string
  - export RELEASE=$(echo "${TRAVIS_TAG}" | sed 's/^v//')
  - mv app/build/outputs/apk/release/yacguide.apk app/build/outputs/apk/release/yacguide-${RELEASE}.apk

deploy:
  provider: releases
  api_key:
    # Generated by the command: travis encrypt <API_TOKEN>
    secure: "VrTY787NgIY3a8Uv/hVuc66Q+PtsDxlSfjKysNwfEz6MSVIclKYTOdeFsEP9OAviLFAIATP2zMYG84TdUhR09xMIP+0AOPNsyplSCJ0EbDn5fhWc3UTwCOr6AlelZ38WYX03oQNVaVI42m2BHkJuUTWdUFXhqlDpXUDttLjwiGHnm1TAcnNRsDAijY02gZLp/ACuhiFEonih/VZuS2Gd7NDPt/zHRQKCvis2bUr8RpN7kIPU3uHiovcGU2U7DKJF/DkZL9bTfMgh4B1ucBz2S8TtFiNcJ2EhH6ktsmgOUXij7MqAh1RkebR+7i7yxBeN80zl/5IAtyfDrt7obI2n11cW8YS0C7Uaj8znTzAsGmYQXuTnh4RIL8JyWbOssD5T0JYBzjHG+jSirNRa7FloP/ShqzpuIYH7MnSxuLlExMDmmpu5CdnxfItDMwcKYNxCPQAR7wmGxGTldNGHd4EmO/Mm15cKU57NZdWRta+4VGh6RpVz8LaaSJewHaqoi6Zy9j3jEkNT02pdRKbaS4AEGd5l1jVWveeaQdRyloX47j71Aq9gcdaSQi+jm4kuVh4vA0nFLBN0qScRrws2RtrppiXmN/d9RiGJZc1TeQHe0SiWsqsuFV3CPj67/TWlW/SyfRGD5ORKznnPfp1Wakv/kp0cNSVxMAB6INQWgbPieRE="
  file: "yacguide-${RELEASE}.apk"
  skip_cleanup: true
  on:
    tags: true
