os: linux
dist: xenial

language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt

services:
  - docker

before_script:
  # Decode Google Service Account JSON file
  - echo $playServicesFileBase64 | base64 -d > $playServicesFile
  # Decode keystore file from variable
  - echo $playKeyStoreBase64 | base64 -d > $playKeyStore
  # Write keystore properties file
  - printf 'storeFile=%s\nstorePassword=%s\nkeyAlias=%s\nkeyPassword=%s\nplayServicesFile=%s\n'
    $playKeyStore $playStorePassword $playKeyAlias $playKeyPassword $playServicesFile > keystore.properties
  # Prepare Docker cotainer
  - scripts/make docker --start-new

script:
  - scripts/make tests
  - scripts/make dists

after_script:
  - scripts/make docker --stop

before_deploy:
  - scripts/make docker --start-existing

deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/make deploy --type dev
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^dev-[0-9]{8}$
  - provider: script
    skip_cleanup: true
    script: scripts/make deploy --type stable
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$

after_deploy:
  - scripts/make docker --stop
