language: minimal

services:
  - docker

env:
  global:
    # The following encrypted variables were created by the commands 'travis encrypt storepass=STORE_PASSWORD'
    - secure: BnZZXqtBbUSKfBtY3zjhiPE7eUcqNmTBz2t1Y6GhPgbXeRVV6/5L/9H3G/DLYKVs9lfbSDUoXCgXMxmSrrvNphhsKUrdizGIH2YXLJZrR2xjtKOIdpV+nCRUUw9oTjGr2tUiKeGo1SCOOqaw+EQXMg0WgR6BcRjiLuAsfMwzQMg33CCWGm6CqhXhDhaIxg9kY001SEoEFrwRuxuOjdSWc7J/7e3Y0ZLqXa+RT8zfk4eIcAbnyA0dt1q1QM9/7fMzLGXLzmETxIkQUx0lqPsxWf2femOWKu1Njg9R6vx8ZeSgFPUNPNAGEJli8Jb0290/3vRYHSLbhVyeh1kMGc0tT7pRfzaqB0WNXrWCuaWG4glD+lxTUENXchC/Db0CwYgcrPfhf4Map85okG0wR8FgyDAHLNFthBv/6anajrpPnyhDXdZwqExgW/x7curJbMH/BUfje4IYfkiwAgCCkwO6s9qCyQZcQvFD21pm8L3JrjPFrcRuJ8Jw3cOc3FOKUMJNuEYYVKMVZFnp7kn19G4F+PRfYT5T2KYgrP5oR/fagvFvbQzOFbU9i5hZzLiZDs21IakJL814l0zt61FavSz+Zvfjw3ZrBqtefQ+NLpcn5WoSUHTXrbtD6m5ZWnuSBJC2dlSvRzSDof23mfmixB+SE0d9hL6zIIsLSK78+YKGj3Q=
    # The following encrypted variables were created by the commands 'travis encrypt keypass=KEY_PASSWORD'
    - secure: UhRzRitGVw7Bi+MJUyY9gZFi/t1XYj8xxZVtIEf/6ujNbVdKDPwg5AhwIJm0UYp4CkmYybcsBlsWT9+JtNBmGS3Jq6U1AeWAZh7FjT/87C3Aq9/zadJwAPrUYUuGjdK44on5CMs1QOPAFopsVK61qoRW34Q2RXeCGTn0/WeitOw1txWxGDG5nIsRcbL2WhAw6N1PfC01rxxysPvTAZmqisB9m5sAIwRFVslyJZ78ebTNRXhhf5yOzp3FwgWpOcRi5JNe0h9m0nmim3TjgJCWeBxqF0mACLvaJ7cSEeWKbLGJWc57md9zCSpo8TRgCQWhJ3zZAf4/iXsLFOiMywrRszauqlLIBQcCElpmYsPHwKx79+q1oPS3ez+3Cx2826lJlWiccAY3iI5Zaf8+2cYPAegkwop83LG4g9mN/B/3n97R8pmyqQ+8NulqLKgAmZQSLTWDMN1J6NE4fPkNI0Rk3ZjwPhfz3MNKd14v2Z4FTSL9vMT96DeMfoquF1klLSoeNRda3qGlPubna4gfOwiL2OKSU9MiZnQlxQg3kCXKSrdRsA64UQMDBu5p0XSoXOf10HhRimh5uxS7flmO1aDFA35H9sFtuh5FHupS8lgO9K5u2bgeyPoM2EyMbtvInnKf9PpDhZMVBQcZlC+k7LXdAT1qVeVXID86LzW4RfLweLM=

before_install:
  # The encrypted keystore file as well as the following command was created by the command 'travis encrypt-file keystore.jks'.
  - "openssl aes-256-cbc -K $encrypted_78b319501daa_key -iv $encrypted_78b319501daa_iv -in keystore.jks.enc -out keystore.jks -d"

script:
  - ./docker/build.sh "$storepass" "$keypass"

before_deploy:
  # Remove leading 'v' from tag name to extract release string
  - export RELEASE=$(echo "${TRAVIS_TAG}" | sed 's/^v//')
  - mv app/build/outputs/apk/release/yacguide.apk app/build/outputs/apk/release/yacguide-${RELEASE}.apk

deploy:
  provider: releases
  api_key:
    # Generated by the command: travis encrypt <API_TOKEN>
    secure: "VrTY787NgIY3a8Uv/hVuc66Q+PtsDxlSfjKysNwfEz6MSVIclKYTOdeFsEP9OAviLFAIATP2zMYG84TdUhR09xMIP+0AOPNsyplSCJ0EbDn5fhWc3UTwCOr6AlelZ38WYX03oQNVaVI42m2BHkJuUTWdUFXhqlDpXUDttLjwiGHnm1TAcnNRsDAijY02gZLp/ACuhiFEonih/VZuS2Gd7NDPt/zHRQKCvis2bUr8RpN7kIPU3uHiovcGU2U7DKJF/DkZL9bTfMgh4B1ucBz2S8TtFiNcJ2EhH6ktsmgOUXij7MqAh1RkebR+7i7yxBeN80zl/5IAtyfDrt7obI2n11cW8YS0C7Uaj8znTzAsGmYQXuTnh4RIL8JyWbOssD5T0JYBzjHG+jSirNRa7FloP/ShqzpuIYH7MnSxuLlExMDmmpu5CdnxfItDMwcKYNxCPQAR7wmGxGTldNGHd4EmO/Mm15cKU57NZdWRta+4VGh6RpVz8LaaSJewHaqoi6Zy9j3jEkNT02pdRKbaS4AEGd5l1jVWveeaQdRyloX47j71Aq9gcdaSQi+jm4kuVh4vA0nFLBN0qScRrws2RtrppiXmN/d9RiGJZc1TeQHe0SiWsqsuFV3CPj67/TWlW/SyfRGD5ORKznnPfp1Wakv/kp0cNSVxMAB6INQWgbPieRE="
  file: "yacguide-${RELEASE}.apk"
  skip_cleanup: true
  on:
    tags: true
